### ISSUE TITLE
Laravel-cachebuster conflicting with Croppa image file generation

### ISSUE THREAD

**Issue by harpster604** [TheMonkeys/laravel-cachebuster#12]
I'm trying to use laravel-cachebuster but it's causing some sort of conflict when also using [BKWLD/croppa](http://github.com/BKWLD/croppa). Croppa automatically generates thumbnails based on the size you specify and saves them in the format: /uploads/file-200x100.jpg

When using the packages together, Croppa is not generating the thumbnails in the specified folder, so the webpage cannot find any of the images being used (404). After a few hours of trying to figure out the issue, I finally narrowed it down to the section of code that the cachebuster doc says to add to the app/routes.php file:

```php
// Cachebuster
Route::get('{path}', function($filename) {
	return Bust::css($filename);
})->where('path', '.*\.css$');
App::make('cachebuster.StripSessionCookiesFilter')->addPattern('|\.css$|');
```

If I remove this from the routes, Croppa generates the images and it works fine. Cachebuster is also working fine. Could you please explain what the purpose of this chunk of code is? Am I okay without having it in? I don't have any interest in using cachebusting for the images (or image paths inside the css). I really only need it for the actual css and js files which seem to working correctly without this.

Thanks!

**Comment by felthy** [comment]
Croppa uses a route with the same signature at [ServiceProvider.php:80](https://github.com/BKWLD/croppa/blob/master/src/Bkwld/Croppa/ServiceProvider.php#L80):

```
	$this->app['router']
			->get('{path}', 'Bkwld\Croppa\Handler@handle')
			->where('path', $this->app['Bkwld\Croppa\URL']->routePattern());
```

That executes first (it's part of the application's boot process), and is then overwritten by the subsequent cachebuster route in `routes.php` because the method (`get`) and pattern (`{path}`) are the same ([RouteCollection::addToCollections()](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/RouteCollection.php#L65)).

What the line in your `routes.php` does is to process your css and replace asset URLs with cachebusted URLs. So you're right that if you aren't interested in cachebusting the assets referenced within your CSS files, you don't need it. Another way you could resolve the issue, while keeping the CSS processing feature of laravel-cachebuster, is to make the cachebuster route more specific. For example:

```
Route::get('/css/{path}', function($filename) {
    return Bust::css("/css/$filename");
})->where('path', '.*\.css');
```

Or you could even use `Bust::css()` within a filter instead.

To resolve this issue I'll update the readme with the above advice.

**Comment by harpster604** [comment]
Awesome! Thanks for the quick reply. It all makes sense now. I will use the updated route then if I decide to use cachebusting on the assets.
